### PR TITLE
INT-1136 add `explain` method, route, and tests.

### PR DESCRIPTION
**Pull request by rueckstiess**
@durran please review. 

It appears that the node driver does not yet support explain verbosity. I left a `@todo` comment in the code explaining that.

---
This change is [Reviewable](https://reviewable.io/reviews/mongodb-js/data-service/7)

### CODE REVIEW

**Comment by rueckstiess** [comment]
Test failure: 
```
  1) NativeClient #explain when a filter is provided returns an explain object for the provided filter:
      Uncaught AssertionError: expected { Object (cursor, isMultiKey, ...) } to contain keys 'queryPlanner', and 'executionStats'
      + expected - actual
       [
      -  "allPlans"
      -  "cursor"
      -  "indexBounds"
      -  "indexOnly"
      -  "isMultiKey"
      -  "millis"
      -  "n"
      -  "nChunkSkips"
      -  "nYields"
      -  "nscanned"
      -  "nscannedAllPlans"
      -  "nscannedObjects"
      -  "nscannedObjectsAllPlans"
      -  "scanAndOrder"
      -  "server"
      +  "executionStats"
      +  "queryPlanner"
       ]
```


The test should not fail against a 3.2 node. These don't seem to have an effect:

```
Setting environment variables from .travis.yml
$ export MONGODB_VERSION=3.2.x
$ export MONGODB_TOPOLOGY=standalone
```


But it's returning an explain output from a 2.6 server ([example](https://docs.mongodb.org/v2.6/reference/method/cursor.explain/#cursor.explain)).

@durran @imlucas any idea why it's not running version 3.2?

**Comment by durran** [comment]
@rueckstiess I enabled debug locally and it looks like if an existing mongod exists, then the version manager does not download anything... Locally it never does for me with my mongod in the path, and I think the code might be here:

https://github.com/mongodb-js/runner/blob/master/lib/index.js#L226

Travis has a 2.6 mongod installed by default.

**Comment by imlucas** [comment]
:arrow_up: mongodb-version-manager@3.2.1 fixes silly bug causing this to fail.

**Comment by imlucas** [comment]
:shipit:

**Comment by imlucas** [comment]
Published in mongodb-data-service@0.0.14

**Comment by rueckstiess** [comment]
Thanks @imlucas  🍰

**Pull request merged**
