### PR TITLE
COMPASS-372 - Refactor Data Service Indexes Getter. [HOLD]

### PR DESCRIPTION
**Pull request by aherlihy**
Includes test fixes for listIndexes on 3.0.x.

### CODE REVIEW

**Comment by aherlihy** [comment]
Failure is perhaps related to [this?](https://github.com/caolan/async/blob/master/CHANGELOG.md#breaking-changes)

**Comment by pzrq** [comment]
@aherlihy Please see https://github.com/mongodb-js/data-service/pull/68 and rebase accordingly, thanks!

**Comment by durran** [comment]
LGTM - Holding for remaining index model work to get completed.

**Comment by pzrq** [comment]
Closing, as the upstream ticket appears to have been closed months ago (feel free to update both if that's not as expected): https://jira.mongodb.org/browse/COMPASS-372

**Pull request closed without merging**
